#!/usr/bin/python3

"""
A simple host calculator for lazy network people.
"""


class Hosts:
    def __init__(self, cider):

        self.cider = int(cider)


        self.subnets = {} #will get populated once imported. (init)

        print('test init ran')
